### ISSUE TITLE
question : how to use it really

### ISSUE THREAD

**Issue by armellarcier** [gayanhewa/sailsjs-cacheman#2]
Hi! I'm looking for a solution to cache queries for a sailsjs app. Could this do the trick and if it can, how to implement it as a middleware on a set of api endpoints?

Quick directions would be awesome.

Thanks and cheers to your work!

**Comment by gayanhewa** [comment]
So within the middleware , you can create an instance 

```
var Cache = require('sailsjs-cacheman').sailsCacheman('name');
```

Use the methods from the documentation here , https://github.com/cayasso/cacheman
